name: CI Proyecto UT4 Angular

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout del código
        uses: actions/checkout@v4

      - name: Configurar Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'

      - name: Instalar dependencias
        run: npm install

      - name: Ejecutar Tests Unitarios (Karma)
        run: npx ng test --watch=false --browsers=ChromeHeadless

      - name: Ejecutar Tests E2E (Cypress)
        uses: cypress-io/github-action@v6
        with:
          start: npm start
          wait-on: 'http://localhost:4200'