name: CI/CD Proyecto UT5 Angular

on:
  push:
    branches: [ main, master ]

jobs:
  build-test-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout del código
        uses: actions/checkout@v4

      - name: Configurar Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'

      - name: Instalar dependencias
        run: npm ci

      - name: Ejecutar Tests Unitarios (Karma)
        run: npx ng test --watch=false --browsers=ChromeHeadless

      - name: Ejecutar Tests E2E (Cypress)
        uses: cypress-io/github-action@v6
        with:
          start: npm start
          wait-on: 'http://localhost:4200'

      # PASO NUEVO PARA LA UT5: Solo se ejecuta si los tests de arriba dan OK
      - name: Deploy to Render
        if: github.ref == 'refs/heads/main'
        run: |
          curl -X POST ${{ secrets.RENDER_DEPLOY_HOOK }}